### ISSUE TITLE
Rendering problem in markdown and Jekyll

### ISSUE THREAD

**Issue by Alanthink** [SaswatPadhi/pseudocode.js#13]
Hi Tate, 

Thanks for the project. I am using it in my own blog built with Jekyll and Minimal theme. When I put the following raw html code in the middle of Markdown file

```html
<pre id="ts" style="display:none">
\begin{algorithmic}
\PRINT \texttt{'hello world'}
\end{algorithmic}
</pre>

<script type="text/javascript">
    var testExamples = document.getElementById("ts").textContent;
    pseudocode.render(testExamples, document.body, {
        lineNumber: true,
        noEnd: false
    });
</script>
```

the output html will put the algorithm in the end of the post like the following:

![image](https://user-images.githubusercontent.com/17557588/57166861-83498b80-6dc9-11e9-9edd-ff38a84cd64c.png)

I will appreciate it a lot if you can provide some helpful suggestions.

Thanks,

Chao

**Comment by Alanthink** [comment]
I have found the reason. I need to change the second parameter of `pseudocode.render` to the element I want my algorithm to be placed at.

**Comment by mendax1234** [comment]
@Alanthink How do you render pseudocode.js in your the minimal theme? Can provide some hints for me. Currently I am stuck at it.
Thanks for any help!
