### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by hubgit** [SaswatPadhi/pseudocode.js#16]
Would it be possible to publish the `pseudocode` package to npm?

**Comment by SaswatPadhi** [comment]
Good idea! Thanks.

I am on it. I plan to release the 2.0 package very soon. I would also publish it to npm then.

**Comment by SaswatPadhi** [comment]
Hi @hubgit,

I just published https://www.npmjs.com/package/pseudocode.
Please let me know if you find any issues.

Thanks.
