### ISSUE TITLE
I18n for "Algorithm" string in caption

### ISSUE THREAD

**Issue by josedusol** [SaswatPadhi/pseudocode.js#18]
The "Algorithm" string appearing in caption title is hardcoded in the [source](https://github.com/SaswatPadhi/pseudocode.js/blob/c223fa56f537b47c9843886d4b6dd4583b20571c/src/Renderer.js#L819). 

Could this be made more flexible for other languages?, maybe adding an option to customize the caption prefix. For example in Spanish is "Algoritmo", and in french is "Algorithme".

Good project. Thanks

**Comment by SaswatPadhi** [comment]
Great idea! Thanks for the suggestion.

I would look into how to best support this for "Algorithm" and other hardcoded strings. If you already have a good idea on how to achieve this, you are most welcome to open a PR.
