### ISSUE TITLE
Support for MathJax

### ISSUE THREAD

**Issue by seba-1511** [SaswatPadhi/pseudocode.js#2]
First of all, thanks a lot for this project. It looks great, and is quite useful.

I was wondering if it would be possible to add support for MathJax, together with KaTex. Although being a bit slower, MathJax would allow to render any equation.

Best,
Séb

**Comment by tatetian** [comment]
I try to maintain this project with a minimal effort. So I won't make changes actively. I would like to accept PRs that can use MathJax as an alternative backend for pseudocode.js.

**Comment by ZJUGuoShuai** [comment]
@seba-1511 @tatetian I made a try on PR #12

**Comment by SaswatPadhi** [comment]
PR #12 has finally been merged :)
