### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by benabel** [SaswatPadhi/pseudocode.js#24]
Hi, and thanks for sharing your code.

I would like to know if I can use this library from the server-side, something like the katex method: `katex.renderToString(...)`.

**Comment by SaswatPadhi** [comment]
Hi @benabel,

Yes, `katex.renderToString()` should work. There are some issues with MathJax rendering, which was reported in #21 and am working on them, but server-side rendering with KaTeX has been reported to work fine (although you might get some warnings).

**Comment by SaswatPadhi** [comment]
Hello,

I have added (in 49b9c6d0e6991d90e5b8408f29543796621abfce) server-side rendering for MathJax 3.x now, using their `tex2chtml` API. `renderToString` should work perfectly with KaTeX and MathJax 3.x backends now.

With MathJax 2.x and below, however, there is no convenient way to achieve it so I won't be adding support for it.

Thanks again for raising this issue!
