### ISSUE TITLE
Problem with repeat...until loop with noEnd: true

### ISSUE THREAD

**Issue by tzok** [SaswatPadhi/pseudocode.js#26]
When `noEnd: true` is set, the _repeat...until_ loop does not render the _until_ line. Although it seems to be working as intended, the _until_ line contains an important part of the algorithm and should never be omitted. It is a different ending statement than _end for_, _end if_, and so on, so it should be treated differently.

I would expect to hide all _end if_, _end for_, and so on with `noEnd: true`, but keep _until_ line regardless.

**Comment by SaswatPadhi** [comment]
Thanks for reporting this @tzok!

I think this would relatively easy to fix, but we want to stay as close as possible to the LaTeX behavior. Do we know how this is handled in LaTeX? I can try it this weekend and see if they handle `until` differently
