### ISSUE TITLE
just a thanks

### ISSUE THREAD

**Issue by ricopicone** [SaswatPadhi/pseudocode.js#28]
Sorry for the improper placement, but I found no other way to thank the contributors. I was making svgs of LaTeX-generated pseudocode for the web. This is so much better! Great work.

**Comment by SaswatPadhi** [comment]
Hi @ricopicone,

Thank you! That's very kind of you! I inherited this project from @tatetian, who deserves all the credit.

I returned from my vacation a couple of weeks ago and I am slowly catching up on all the issues and PR.
