### ISSUE TITLE
renderElement TypeError when backend doesn't exist

### ISSUE THREAD

**Issue by ricopicone** [SaswatPadhi/pseudocode.js#29]
I'm getting the following error.
![image](https://user-images.githubusercontent.com/4192991/153793791-f0f0c567-fb8e-4bad-a505-8073ecb8d5cd.png)

I'm using URLSearchParams like that visible in the error, `?TS=T1&DS=`, and it seems this might be where the trouble lies. Interestingly, the algorithm still renders properly.

Any ideas?

**Comment by ricopicone** [comment]
Sorry, the obscured part reads `read properties of undefined (reading 'name') at Object.renderElement`

**Comment by ricopicone** [comment]
Update: only the first algorithm to appear on the page renders properly, which makes sense because it looks like it's an error in a for loop.

**Comment by ricopicone** [comment]
The PR above fixes the issue, which in the end had nothing to do with the url search parameters. Rather, no `renderer.backend` existed, so `renderer.backend.name` gave the error.

**Comment by SaswatPadhi** [comment]
Many thanks for debugging this issue and for the PR!

**Comment by ricopicone** [comment]
My pleasure!
