### ISSUE TITLE
Render Elements By Class Name

### ISSUE THREAD

**Issue by zcysxy** [SaswatPadhi/pseudocode.js#31]
I would like to use this in Markdown, like

~~~markdown
```pseudo
some algorithms
```
~~~

And this gives the `<pre>` element a `"pseudo"` class. So it would be great to support `getElementsByClassName`.

**Comment by SaswatPadhi** [comment]
Hi @zcysxy, That's a great idea, thanks! Would you like to submit a PR for this?

I would have some time towards the end of the month, hopefully.

**Comment by zcysxy** [comment]
Honestly I'm not familiar with javascript. But I may look into it
