### ISSUE TITLE
pseudocode.renderClass is undefined

### ISSUE THREAD

**Issue by ginqi7** [SaswatPadhi/pseudocode.js#36]
when I operate accoding to the README, i meet a problem is 

*pseudocode.renderClass* is undefined
![image](https://user-images.githubusercontent.com/1028971/187341934-580a1535-41f5-4f58-9ad2-1448519ffeb2.png)

and *pseudocode.renderElement* is ok.

![image](https://user-images.githubusercontent.com/1028971/187342060-5506463e-9af9-4291-bfe6-837f67120ba4.png)

**Comment by SaswatPadhi** [comment]
Hello,

I believe this error is because the pseudocode.js builds available on jsdelivr CDN are old.

The `renderClass` method was added recently (in #32) and I haven't yet pushed a new release for pseudocode.js. Thanks for noticing this. I will push a new build shortly.

**Comment by ginqi7** [comment]
ok, I close this issue and will try new version later. thank you for your reply.

**Comment by roife** [comment]
It seems that the version on the CDN has not been updated yet.

Any updates recently?

**Comment by SaswatPadhi** [comment]
Hello,

Sorry about the delay. I just merged a pending PR and fixed a bunch of small issues, then pushed 2.3.0. The `latest` from CDN should now contain the `renderClass` API.

**Comment by femtomc** [comment]
Running into the following issue with this:
<img width="481" alt="image" src="https://github.com/SaswatPadhi/pseudocode.js/assets/34410036/e8897cfc-8e0b-47d8-b48d-114f29aa7b0d">

**Comment by SaswatPadhi** [comment]
Hi @femtomc,

I just pushed v2.4.1 with a fix for this and the other bug you reported.
I have also added a test for `renderClass` now.

Please see https://jsfiddle.net/wz5r6cy9/ for a test.
