### ISSUE TITLE
Enable scopeLines (sidelines)

### ISSUE THREAD

**Issue by marcosroriz** [SaswatPadhi/pseudocode.js#38]
I think scope lines (not sure if it is the ‘formal name’) can be used to clarify algorithms. For instance, the screenshot below illustrates two algorithms with this functionality. Hence, I think it can be useful to enable the library to include this functionality. I implemented the changes and I’m doing a pull request for your consideration. The change basically adds an optional argument named scopeLines (false by default) that render the sidelines.

![image](https://user-images.githubusercontent.com/1276322/210044964-1c5fd8d4-fee4-4836-ad69-e138a30df5ae.png)

**Comment by SaswatPadhi** [comment]
Thanks again for the PR!

Merged #39; resolving this.
