### ISSUE TITLE
Any instructions on how to use this with marp https://marp.app/

### ISSUE THREAD

**Issue by tjtaill** [SaswatPadhi/pseudocode.js#40]
I really like this tool would love to use it with marp https://marp.app/ though, I have managed to use mermaid.js with marp
wondering if would have any guidance on how use this with marp ?

**Comment by tjtaill** [comment]
This seems to work now struggling with text size \small \scriptsize doesn't seem to work well stops rendering

**Comment by SaswatPadhi** [comment]
Hi @tjtaill,

> This seems to work now struggling with text size \small \scriptsize doesn't seem to work well stops rendering

Could you please give some more details? If you could share a link to your page that would be helpful. Thanks.

**Comment by tjtaill** [comment]
> Hi @tjtaill,
> 
> > This seems to work now struggling with text size \small \scriptsize doesn't seem to work well stops rendering
> 
> Could you please give some more details? If you could share a link to your page that would be helpful. Thanks.

Hi I was able to get it to work by introducing this block of css in my marp markdown file

```html
<style scoped>
  .ps-root {
    font-size: .45em;
  }
  p {
    margin-bottom: 5px;
  }
</style>
```

Thanks you can close this issue

**Comment by SaswatPadhi** [comment]
Glad that you were able to fix it!

My guess is that some Marp-specific style is probably overriding the default pseudocode.css style. I'd be happy to investigate further if you point me to your page / presentation at some point.

Closing this for now.
