### ISSUE TITLE
MathJax 4.0

### ISSUE THREAD

**Issue by sebsciarra** [SaswatPadhi/pseudocode.js#44]
I am trying to use `pseudocode.js` with MathJax 4.0. I have followed all the four steps listed in the ReadMe file, but cannot seem to get it to work with MathJax 4.0. Here is how I call MathJax 4.0: 

```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-alpha.1/es5/tex-mml-chtml.js"
        integrity="9df6fbc821287c8717485c417ee18bde3f94a30d18d2dec88c29200806c7dabe"
        crossorigin="anonymous" referrerpolicy="no-referrer">
</script>
```

**Comment by SaswatPadhi** [comment]
Hi, thanks for the report.

I was able to test on my machine and indeed MathJax 4.0 back end doesn't seem compatible. I am looking into it.

**Comment by SaswatPadhi** [comment]
Hi,

I pushed some changes to make pseudocode work with MathJax 4.x as well.
You can see a working sample page here: https://saswat.padhi.me/pseudocode.js/mathjax-v4-samples.html.

It's not the most elegant solution, and I haven't released a new version, but could you try the [docs/pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js/blob/master/docs/pseudocode.js) file and let me know if you notice any issues?

I saw your thread on the MathJax repo as well. Thanks for starting the discussion there. I'll comment on that thread to see if the MathJax devs have some suggestions.

**Comment by sebsciarra** [comment]
Ok, I have tried  two attempts with no success. 

First attempt: In my`<head>` file, I used 
```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-chtml.js"
              integrity="sha256-ljPODBK7Jf/VfUrVqec63xzZbysEmwB9Ab20TWRMQRU="
              crossorigin="anonymous">

      </script>
     <script src="{{ "js/pseudocode.js" | relURL }}"></script>
```
 which yielded a semi-rendered version of the pseudocode (see attached image)
<img width="374" alt="semi-rendered" src="https://github.com/SaswatPadhi/pseudocode.js/assets/85191660/680785ea-5325-437f-85ac-27ae3617ff2a">

Second attempt: I loaded the `pseudocode.js` from the directory, but had no success. 
```html
  <script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-chtml.js"
          integrity="sha256-ljPODBK7Jf/VfUrVqec63xzZbysEmwB9Ab20TWRMQRU="
          crossorigin="anonymous">

  </script>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css">
<script src="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js">
</script>
```

My only success has been using 
```html
 <script src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml-full.js"
        integrity="sha256-kbAFUDxdHwlYv01zraGjvjNZayxKtdoiJ38bDTFJtaQ="
        crossorigin="anonymous">
</script>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css">
<script src="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js">
</script>
```

**Comment by SaswatPadhi** [comment]
Hi,

Thanks for testing.

The first attempt should work (that's what the v4 samples does), but it's asynchronous so you'll have to wait (a few seconds) for the algorithm to fully render.

Can you also let me know if this page (https://saswat.padhi.me/pseudocode.js/mathjax-v4-samples.html) fully renders within a few seconds on your machine?

The second attempt shouldn't work. It's usually the old pseudocode.js without MathJax 4.0 support.

The third attempt uses MathJax 3 and should work.

**Comment by sebsciarra** [comment]
Hmm ok! Made a couple of fixes and you are correct. Got the first method to work! And yes the link works perfectly for me! Appreciate the fast responses!
