### ISSUE TITLE
Color of horizontal Lines incompatible with dark Mode

### ISSUE THREAD

**Issue by Mavoort** [SaswatPadhi/pseudocode.js#47]
On a web page with white text and a dark background ("dark mode"), the pseudocode block looks a bit strange.

In particular, the horizontal lines remain black, even though the text and the vertical lines are  white.

![pseudocode_bug-black_lines](https://github.com/SaswatPadhi/pseudocode.js/assets/46296384/e7935209-e995-4360-91c4-251b855a0d25)

To fix this, I suggest replacing 
```css
border: 2px solid black;
```
inside of `pseudocode.css` with:
```css
border-width: 2px;
border-style: solid;
```
This way you could use pseudocode.js also on a dark website.

**Comment by SaswatPadhi** [comment]
Thanks for reporting this issue, @Mavoort!

I have reviewed your changes and left some minor comments. I've also linked your PR to this bug so this issue will be closed automatically when we merge your change.
