### ISSUE TITLE
Completely hide caption prefix

### ISSUE THREAD

**Issue by HaydarJawad** [SaswatPadhi/pseudocode.js#50]
Great package I love it thank you ! is there a way force  the  **Algorithm 1** part of the caption to my own words  ? 
**Algorithm 1** New Quicksort

Regards 
Haydar

**Comment by SaswatPadhi** [comment]
Hi Haydar,

You could use the `titlePrefix` option to override that. I had introduced it in 69528e9bf5ecbacbe5f4094ca61c654fdf85f71b, but I just noticed that it's not mentioned in the README.md file. I will add it under https://github.com/SaswatPadhi/pseudocode.js/blob/master/README.md#global-options.

**Comment by HaydarJawad** [comment]
Thank you mate, I tried this and now I keep getting (1) when I render the
html on the browser instead of nothing ?

I want to decide the title myself,
Regards
Haydar
Start :


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pseudocode Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css">
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml-full.js" integrity="sha256-kbAFUDxdHwlYv01zraGjvjNZayxKtdoiJ38bDTFJtaQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js"></script>
    <style>
        .pseudocode .caption {
            display: none;
        }
    </style>
</head>
<body>
    <h1>Quicksort</h1>
    <pre id="quicksort" class="pseudocode">
        % This quicksort algorithm is extracted from Chapter 7, Introduction to Algorithms (3rd edition)
        \begin{algorithm}
        \caption{}
        \begin{algorithmic}
        \PROCEDURE{Quicksort}{$A, p, r$}
            \IF{$p < r$}
                \STATE $q = $ \CALL{Partition}{$A, p, r$}
                \STATE \CALL{Quicksort}{$A, p, q - 1$}
                \STATE \CALL{Quicksort}{$A, q + 1, r$}
            \ENDIF
        \ENDPROCEDURE
        \PROCEDURE{Partition}{$A, p, r$}
            \STATE $x = A[r]$
            \STATE $i = p - 1$
            \FOR{$j = p$ \TO $r - 1$}
                \IF{$A[j] < x$}
                    \STATE $i = i + 1$
                    \STATE exchange $A[i]$ with $A[j]$
                \ENDIF
            \ENDFOR
            \STATE exchange $A[i]$ with $A[r]$
        \ENDPROCEDURE
        \end{algorithmic}
        \end{algorithm}
    </pre>

    <script>
        pseudocode.renderElement(document.getElementById("quicksort"), { titlePrefix: "", captionCount: 0 });
    </script>
</body>
</html>
ENd

**Comment by SaswatPadhi** [comment]
Hi,

I understand your question now.
To completely hide the caption prefix, you could add the following do your `<style>`:

```css
.ps-algorithm.with-caption > .ps-line > .ps-keyword {
  display: none;
}
```

You also don't need to override the `titlePrefix` or the `captionCount`.

Here is an example: https://jsfiddle.net/sx374h1b/

**Comment by HaydarJawad** [comment]
Thank you mate, that's exactly what I wanted.
Regards
Haydar

**Comment by SaswatPadhi** [comment]
Great! :) Glad I could help.

Closing this issue.
