### ISSUE TITLE
Update to KaTex-0.8

### ISSUE THREAD

**Issue by SamuelLarkin** [SaswatPadhi/pseudocode.js#6]
Hi @tatetian ,
nice work, I was hoping to use your code to format my pseudo code it looks like there hasn't been any activity for long while.  I was wondering if you could build a new version with newer KaTex?  I would like to have \mathcal{}, \right & \left working to name a few.

T.I.A.

**Comment by tatetian** [comment]
Hi @SamuelLarkin ,

You request is at a very good timing. I am planning to do some upgrade to the dependencies of pseudocode.js. I am going to test it with the latest version of Katex.

Thanks,
Tate

**Comment by tatetian** [comment]
Check out the release of version 1.1. It works fine with KaTeX 0.9 beta.

**Comment by SamuelLarkin** [comment]
Thanks for the quick response.  It's great and it works for me.
