### ISSUE TITLE
Support `\repeat`?

### ISSUE THREAD

**Issue by iblislin** [SaswatPadhi/pseudocode.js#7]
Algorithmic's doc has `\repeat`, but seems pseudocode.jl not?
http://tug.ctan.org/macros/latex2e/contrib/algorithmicx/algorithmicx.pdf

**Comment by tatetian** [comment]
No, the current implementation does not support \repeat or \loop. Thanks for pointing out.

Adding these statements should be easy. I will add them in a few days. Or if you want this feature ASAP, you can do it yourself. I am happy to accept PRs.

**Comment by iblislin** [comment]
Ha, I can wait. Takes your time :)

**Comment by ZJUGuoShuai** [comment]
@iblis17 @tatetian I just made a PR and tested it. It worked well, I think. #10

**Comment by tatetian** [comment]
#10 is merged. Thanks for the contribution @ZJUGuoShuai .
