### ISSUE TITLE
Uppercase variables

### ISSUE THREAD

**Issue by Steditor** [SaswatPadhi/pseudocode.js#9]
Pseudocode currently seems to lowercase all variables in tex code, as can be seen on the project website (note that the first argument, `a`, in the quicksort algorithm is uppercase in the code, but lowercase in the output).

**Comment by tatetian** [comment]
You're right. This is a bug, but it has been fixed since v1.1. Unfortunately, the demo site has not been updated. So just use the latest code.

**Comment by Steditor** [comment]
Ah, I see - thanks for the tip! We now managed to update the plugin on our page and everything works fine. I guess this issue can then be either closed or rededicated to updating the demo site.
